version: '3.7'

services:
    nginx:
       image: nginx:alpine
       volumes:
           - ./data:/etc/nginx/conf.d/
           - /var/run/docker.sock:/tmp/docker.sock:ro
       ports:
           - 80:8080
       networks:
           - reverse-proxy
       restart: always

networks:
  reverse-proxy:
