version: '3.7'

services:
  nodebb11x:
    image: vimagick/nodebb
    ports:
      - "4411:4411"
    expose:
      - 4411
    environment:
      - VIRTUAL_HOST=kode11.my.id
    networks:
      - nginx_reverse-proxy
      - backend1
    volumes:
      - ./data:/var/lib/nodebb
      - /usr/src/nodebb/build
      - /usr/src/nodebb/node_modules
      - ./data/uploads:/usr/src/nodebb/public/uploads
    restart: always

  mongo11:
    image: "mongo:latest"
    command: mongod --port 28011
    networks:
      - backend1
    ports:
      - "28011:28011"
    volumes:
      - ./data/mongodb/db:/data/db
    restart: always

networks:
    backend1:
    nginx_reverse-proxy:
       external: true
